const players = [
    {
        name: 'Lionel Messi',
        team: 'Paris Saint-Germain',
        nationality: 'Argentine',
        jerseyNumber: 30,
        age: 34,
        imageUrl: 'https://res.cloudinary.com/dhwqlht1d/image/upload/v1708441111/machester%20players/711_j4da24.webp',
    },
    {
        name: 'Cristiano Ronaldo',
        team: 'Manchester United',
        nationality: 'Portuguese',
        jerseyNumber: 7,
        age: 36,
        imageUrl: 'https://res.cloudinary.com/dhwqlht1d/image/upload/v1707220491/machester%20players/ronaldo_uwszop.jpg',
    },
    {
        name: 'Neymar Jr.',
        team: 'Paris Saint-Germain',
        nationality: 'Brazilian',
        jerseyNumber: 10,
        age: 29,
        imageUrl: 'https://res.cloudinary.com/dhwqlht1d/image/upload/v1708441268/machester%20players/download_12_sf9qln.jpg',
    },
    {
        name: 'Kylian Mbappe',
        team: 'Paris Saint-Germain',
        nationality: 'French',
        jerseyNumber: 7,
        age: 23,
        imageUrl: 'https://res.cloudinary.com/dhwqlht1d/image/upload/v1708439562/machester%20players/images_6_yrlcaj.jpg',
    },
    {
        name: 'Mohamed Salah',
        team: 'Liverpool',
        nationality: 'Egyptian',
        jerseyNumber: 11,
        age: 29,
        imageUrl: 'https://res.cloudinary.com/dhwqlht1d/image/upload/v1708439675/machester%20players/MSalah2023_lt3omw.webp',
    },
    {
        name: 'Robert Lewandowski',
        team: 'Bayern Munich',
        nationality: 'Polish',
        jerseyNumber: 9,
        age: 33,
        imageUrl: 'https://res.cloudinary.com/dhwqlht1d/image/upload/v1708439837/machester%20players/download_5_bjbjce.jpg',
    },
    {
        name: 'Kevin De Bruyne',
        team: 'Manchester City',
        nationality: 'Belgian',
        jerseyNumber: 17,
        age: 30,
        imageUrl: 'https://res.cloudinary.com/dhwqlht1d/image/upload/v1708439837/machester%20players/download_5_bjbjce.jpg',
    },
    {
        name: 'Sadio Mane',
        team: 'Liverpool',
        nationality: 'Senegalese',
        jerseyNumber: 10,
        age: 29,
        imageUrl: 'https://res.cloudinary.com/dhwqlht1d/image/upload/v1708439963/machester%20players/download_6_vuiqnc.jpg',
    },
    {
        name: 'Luis Suarez',
        team: 'Atletico Madrid',
        nationality: 'Uruguayan',
        jerseyNumber: 9,
        age: 35,
        imageUrl: 'https://res.cloudinary.com/dhwqlht1d/image/upload/v1708439972/machester%20players/download_7_uxjcyi.jpg',
    },
    {
        name: 'Harry Kane',
        team: 'Tottenham Hotspur',
        nationality: 'English',
        jerseyNumber: 10,
        age: 28,
        imageUrl: 'https://res.cloudinary.com/dhwqlht1d/image/upload/v1708439982/machester%20players/dfl-obj-j00zz3-dfl-clu-00000g-dfl-sea-0001k7_jrtqch.webp',
    },
    {
        name: 'Virgil van Dijk',
        team: 'Liverpool',
        nationality: 'Dutch',
        jerseyNumber: 4,
        age: 30,
        imageUrl: 'https://res.cloudinary.com/dhwqlht1d/image/upload/v1708440192/machester%20players/images_7_s9xrk7.jpg',
      },
      {
        name: 'Eden Hazard',
        team: 'Real Madrid',
        nationality: 'Belgian',
        jerseyNumber: 7,
        age: 31,
        imageUrl: 'https://res.cloudinary.com/dhwqlht1d/image/upload/v1708441194/machester%20players/be03ef7374b30a376096e3f59d5f2af6_pzv3yk.jpg',
      },
      {
        name: 'Luka Modric',
        team: 'Real Madrid',
        nationality: 'Croatian',
        jerseyNumber: 10,
        age: 36,
        imageUrl: 'https://res.cloudinary.com/dhwqlht1d/image/upload/v1708440352/machester%20players/download_9_ypsg19.jpg',
      },
      {
        name: 'Sergio Ramos',
        team: 'Paris Saint-Germain',
        nationality: 'Spanish',
        jerseyNumber: 4,
        age: 35,
        imageUrl: 'https://res.cloudinary.com/dhwqlht1d/image/upload/v1708440361/machester%20players/download_10_mavmou.jpg',
      },
      {
        name: 'Andrew Robertson',
        team: 'Liverpool',
        nationality: 'Scottish',
        jerseyNumber: 26,
        age: 28,
        imageUrl: 'https://res.cloudinary.com/dhwqlht1d/image/upload/v1708440480/machester%20players/download_11_goxwlg.jpg',
      },
  ];
  
  export default players;